### ISSUE TITLE
Image Pull Backoff error observed when running frequent unzipped data backup

### ISSUE THREAD

**Issue by Aaaaazzaa** [operate-first/curator#66]
**Description**: 

When applying cronjob.yaml with a high backup rate (eg every 5 minutes), `docker.io/minio/mc` failed at the image creation stage: `You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limits.`

**Reason**:

[Docker Hub Rate Limiting](https://www.docker.com/increase-rate-limits): On November 20, 2020, rate limits anonymous and free authenticated use of Docker Hub went into effect. Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours.

**Possible Solution**:

Avoid redundant image pulling by adding `imagePullPolicy: IfNotPresent` for all `containers`. 

```yaml
containers:
  ...
  - name: mc
    image: docker.io/minio/mc
    imagePullPolicy: IfNotPresent
    ...
```
